site_name: TweetBrain Docs
site_url: https://docs.tweetbrain.tisuela.com/

repo_url: https://github.com/tweetbrain/you
repo_name: tweetbrain/you

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - pymdownx.tabbed
